# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('firm_name', models.CharField(max_length=20)),
                ('reference', models.CharField(max_length=200)),
                ('chu', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('interest', models.CharField(max_length=200)),
                ('skils', models.TextField()),
                ('experience', models.TextField()),
            ],
        ),
    ]
