# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20160730_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='name',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='email',
            field=models.EmailField(default='alu', max_length=255, unique=True, verbose_name=b'email address'),
            preserve_default=False,
        ),
    ]
