# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('interest', models.CharField(max_length=200)),
                ('skils', models.TextField()),
                ('experience', models.TextField()),
            ],
        ),
    ]
