# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_board', '0002_freelancer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Freelancer',
        ),
    ]
